---
title: "Country Comparisions"
author: "Moises Evangelista"
date: "Prepared `r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    fig_crop: no
    toc: true
    toc_depth: 2
subtitle: Report Validation
fontsize: 11pt
header-includes:
- \usepackage{palatino}
- \renewcommand{\familydefault}{\sfdefault}
- \fontfamily{ppl}\selectfont

- \usepackage{xcolor}
- \usepackage[normalem]{ulem}
- \hypersetup{colorlinks,urlcolor=blue, linkcolor=black}
- \usepackage{float}
- \PassOptionsToPackage{obeyspaces}{url}
- \usepackage{graphicx, array, blindtext, longtable, tikz}
- \usepackage[export]{adjustbox}

---


\makeatletter 
\begingroup \lccode`+=32 \lowercase
 {\endgroup \def\Url@ObeySp{\Url@Edit\Url@String{ }{+}}}
 \def\Url@space{\penalty\Url@sppen\ }
\makeatother


in this analysis I'm using some of the code found here https://nowosad.github.io/post/maps-distortion/. In addition to viewing each county by the actual area size, I want to view them by the size based on their global GDP and population

```{r setup, include=FALSE}


# the latex code above is to keep spaces in file paths
knitr::opts_chunk$set(cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE,
                      #dpi = 500
                      dev = "cairo_pdf")
rm(list = ls()) #start with empty workspace
# setwd("~/GitHub/MullerReportAnalysis") # set the working directory
# list.files()
library(tidyverse)
library(rnaturalearth)
library(rnaturalearthdata)
library(rvest)
library(data.table)
library(sf)
library(cartogram)
library(gganimate)

# library(RSelenium)
library(XML)
options(scipen = 999)

```

```{r getGDPAndPopData}


gdp <- read_html(httr::GET("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)", httr::user_agent("myagent"))) %>%
  html_table(fill = TRUE, header = NA)

gdpCombo <- gdp %>% 
  .[[3]] %>% 
  mutate(type = "IMF_2018") %>% 
  bind_rows(gdp %>% 
              .[[4]] %>% 
              mutate(type = "WoldBank_2017") #%>% View("test") 
  ) %>% 
  bind_rows(gdp %>% 
              .[[5]] %>% 
              mutate(type = "UnitedNations_2017")) %>% 
  mutate(gdp_USMill = as.numeric(gsub(",","", `GDP(US$million)` )),
         sovereignt = gsub("\\s*\\[.*\\]","",  `Country/Territory`),#    gsub("?[a-z]{1}/.*", "",),
         sovereignt = trimws(sovereignt),
         sovereignt = case_when(sovereignt==  "United States" ~  "United States of America",
                                sovereignt ==  "Korea, South" ~  "South Korea",
                                TRUE ~ sovereignt )
  ) 

rm(gdp)

world_orig  <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  filter(scalerank == 1 ) %>% 
  arrange(desc(gdp_md_est)) %>% 
  slice(1:20) %>% 
  select(sovereignt, admin, gdp_md_est, pop_est, geometry)

class(world_orig )

world_poly = world_orig  %>% 
  st_cast("POLYGON") %>% 
  rmapshaper::ms_filter_islands(.)

world = world_poly %>% 
  st_transform(crs = 3857)

world_areas = world %>% 
  st_transform(crs = "+proj=moll") %>% 
  st_area() %>% as.vector()

map_areas = world %>% 
  st_set_crs(NA) %>% 
  st_area()

world_scaled = world %>% 
  mutate(scale = 1 / (sqrt(map_areas / world_areas))) %>% 
  mutate(scale = as.numeric(scale / max(scale)))

summary(world_scaled$scale)

1 / min(world_scaled$scale)

scaler = function(x, y, z) {
  (x - z) * y + z
}

world_geom = st_geometry(world)

world_center = st_centroid(world_geom)


world_transf = pmap(list(world_geom, world_scaled$scale, world_center), scaler) %>% 
  st_sfc(crs = st_crs(world)) %>% 
  st_sf()


plot(world$geometry)
plot(world_transf$geometry)

world$state = 1
world_transf$state = 2

worlds = rbind(world %>% 
                 select(state, sovereignt)
               , world_transf %>% 
                 mutate(sovereignt = world$sovereignt))

countries <- worlds$sovereignt %>% unique()

plot_list = list()

for (i in seq_along(countries)) {
  p = world_transf %>% 
    mutate(sovereignt = world$sovereignt,
           state = "2") %>% 
    filter( sovereignt == countries[i]) %>% 
    # left_join(gdpCombo %>% 
    #             filter(type == "IMF_2018" )) %>% # View("test")
    # # cartogram_cont( "gdp_USMill", itermax = 5) %>% 
    #    format_n = scales::comma(gdp_USMill),
    #    label = scales::comma(gdp_USMill)) %>% 
    ggplot() +
    geom_sf(aes(fill = state)
            #,fill = NA
            ,alpha = .5
            ,size = .1
    ) +
    geom_sf(data = world %>% 
              select(state, sovereignt) %>% 
              filter( sovereignt == countries[i]) %>% 
              mutate(state = "1"),
            aes(fill = state)
            #,fill = NA
            ,alpha = .5
            ,size = .1
    ) +
    scale_fill_brewer(name = "Map Projections"
                      ,labels = c("Distortion","Real")
                      , type = "seq"
                      , palette = "Dark2"
                      , direction = 1,
                      aesthetics = "fill") +
    theme_minimal() +
    labs(title = countries[i]) +
    theme(legend.position="top")
  
  plot_list[[i]] = p
}

Cairo::CairoPDF(file = "./countriesProjections.pdf",
                #units = "in", dpi = 150,
                width = 12, 
                height = 12, 
                pointsize = 25)

for (i in seq_along(countries)) {
  print(plot_list[[i]])
}

world_scaled  %>%
  mutate(sovereignt = world$sovereignt) %>%
  rmapshaper::ms_dissolve("sovereignt") %>%
  mutate(gdp_md_est = world_orig$gdp_md_est) %>%
  cartogram_cont(., weight = "gdp_md_est") %>%
  mutate(
    format_n = scales::comma(gdp_md_est),
    label = scales::comma(gdp_md_est)) %>%
  ggplot() +
  geom_sf(aes(fill = label)
          #,fill = NA
          ,alpha = .5
          ,size = .1
  ) +
  geom_sf(data = world_orig,
          #aes(fill = label)
          color = "blue"
          ,fill = NA
          ,alpha = .5
          ,size = .1
  ) +
  theme_minimal()

world_scaled  %>%
  mutate(sovereignt = world$sovereignt) %>%
  rmapshaper::ms_dissolve("sovereignt") %>%
  mutate(pop_est = world_orig$pop_est) %>%
  cartogram_cont(., weight = "pop_est") %>%
  mutate(
    format_n = scales::comma(pop_est),
    label = scales::comma(pop_est)) %>%
  ggplot() +
  geom_sf(aes(fill = label)
          #,fill = NA
          ,alpha = .5
          ,size = .1
  ) +
  geom_sf(data = world_orig,
          #aes(fill = label)
          color = "blue"
          ,fill = NA
          ,alpha = .5
          ,size = .1
  ) +
  theme_minimal() 

dev.off()


plot(world %>% 
       select(state, sovereignt) %>% 
       filter( sovereignt == "United States of America") %>% .$geometry
    # , col = sf.colors(12, categorical = TRUE)
    , border = 'grey', 
     ,axes = TRUE)

plot(world_transf %>% 
                 mutate(sovereignt = world$sovereignt) %>% 
       filter( sovereignt == "United States of America") %>% .$geometry
     , pch = 3, border = 'red'
   , add = TRUE
     )

```